In [2]:
import numpy as np
import math

In [3]:
def factorial(number):
    if(number == 0):
        return 1
    elif(number == 1):
        return 1
    return number * factorial(number -1)

In [4]:
factorial(3)

6

In [5]:
def exponantial(number, exp):
    if(exp == 0):
        return 1
    return number * exponantial(number, (exp-1))

In [6]:
exponantial(5,3)

125

In [66]:
# f(x) = sin(2x), 
# f'(x) = 2cos(2x) = 0
# f''(x) = -4sin(2x) = -4
# f'''(x) = -8cos(2x) = 0
# f''''(x) = 16sin(2x) = 16
# f'''''(x) = 32cos(2x) = 0
# 1 - (4*(x - (pi / 4) ^ 2) / (2!)) + (16*(x - (pi / 4) ^ 4) / (4!))

def taylorSeries(x):
    result = 1 - (4/factorial(2))*exponantial((x-(math.pi/4)),2)  + (16/factorial(4))*(exponantial((x-(math.pi/4)),4))
    f = math.sin(2*x)
    return result,f

t,f = taylorSeries(5)

# f(x) = sin(2x), f(5) = sin10

#f = math.sin(10)
print("Taylor result : ",t,"\nFunction result : ", f)

# error is t - f 
e = t - f

print('Error is : ', e)

Taylor result :  175.8205976249771 
Function result :  -0.5440211108893698
Error is :  176.36461873586646


In [28]:
# Gauss Elimination

def gaussElimination(a,b):
    n = len(b)
    for k in range(0,n-1):
        for i in range(k+1,n):
            if a[i,k] != 0.0:
                lam = a[i,k]/a[k,k]
                a[i,k+1:n] = a[i,k+1:n] - lam*a[k,k+1:n]
                b[i] = b[i] - lam*b[k]
    for k in range(n-1,-1,-1):
        b[k] = (b[k] - np.dot(a[k,k+1:n],b[k+1:n]))/a[k,k]
    return b

In [29]:
A = np.array([[ 2.0, -3.0, -1.0] ,[ 3.0, 2.0, -5.0], [ 2.0, 4.0, -1.0]])
b = np.array([[3.0], [-9.0], [-5.0]])

# Result
gaussElimination(A,b)

array([[ 0.65306122],
       [-1.14285714],
       [ 1.73469388]])

In [30]:
# Dootlittle's LU Decompositions

def doolittlesDecomp(a):
    n = len(a)
    for k in range(0,n-1):
        for i in range(k+1,n):
            if a[i,k] != 0:
                lam = a[i,k]/a[k,k]
                a[i,k+1:n] = a[i,k+1:n] - lam*a[k,k+1:n]
                a[i,k] = lam
    return a

def doolittleSolve(a,b):
    n = len(a)
    for k in range(1,n):
        b[k] = b[k] - np.dot(a[k,0:k],b[0:k])
    b[n-1] = b[n-1] / a[n-1,n-1]
    for k in range(n-2,-1,-1):
        b[k] = (b[k] - np.dot(a[k,k+1:n],b[k+1:n]))/a[k,k]
    return b

In [31]:
AA = np.array([[ 2.34, -4.10, 1.78] ,[ -1.98, 3.47, -2.22], [ 2.36, -15.17, 6.18]])
bb = np.array([[0.02], [-0.73], [-6.63]])

# Result
Ap = doolittlesDecomp(AA)
doolittleSolve(Ap,bb)

array([[1.],
       [1.],
       [1.]])

In [33]:
# Choleski Decomposition

def isPosDef(x):
    return np.all(np.linalg.eigvals(x) > 0)

def choleskiDecomp(a):
    n = len(a)
    for k in range(n):
        a[k,k] = math.sqrt(a[k,k] - np.dot(a[k,0:k],a[k,0:k]))
        if isPosDef(a) is False:
            print("Matrix is not positive definite")
            break
        for i in range(k+1,n):
            a[i,k] = (a[i,k] - np.dot(a[i,0:k],a[k,0:k]))/a[k,k]
    for k in range(1,n):
        a[0:k,k] = 0.0
    return a

def choleskiSol(L,b):
    n = len(b)
    for k in range(n):
        b[k] = (b[k] - np.dot(L[k,0:k],b[0:k]))/L[k,k]
    for k in range(n-1,-1,-1):
        b[k] = (b[k] - np.dot(L[k+1:n,k],b[k+1:n]))/L[k,k]
    return b

In [34]:
AAA = np.array([[ 1.0, 1.0, 1.0] ,[ 1.0, 2.0, 2.0], [ 1.0, 2.0, 3.0]])
bbb = np.array([[1.0], [3/2], [3.0]])

#Result
L = choleskiDecomp(AAA)
choleskiSol(L,bbb)

array([[ 0.5],
       [-1. ],
       [ 1.5]])